version: '3'
services:
 dbos:
  image: mysql:5.7
  restart: always
  volumes:
   - mysql_storage_new:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: rootpass
   MYSQL_USER: gautam
   MYSQL_PASSWORD: redhat
   MYSQL_DATABASE: mydb

 wpos:
  image: wordpress:5.1.1-php7.3-apache       
  restart: always
  depends_on:
   - dbos
  ports:
   - 8081:80       
  volumes: 
   - wp_storage_new:/var/www/html
  environment:
   WORDPRESS_DB_HOST: dbos
   WORDPRESS_DB_USER: gautam
   WORDPRESS_DB_PASSWORD: redhat
   WORDPRESS_DB_NAME: mydb

volumes:
  wp_storage_new:
  mysql_storage_new:        
